utils::Image
cv::Mat utils::Image::image_
utils::Image::Image(const std::string &path)
create a new image object
int utils::Image::width()
image width
Referenced by cds::mod::ModAlbums::import.
int utils::Image::height()
image height
Referenced by cds::mod::ModAlbums::import.
std::string utils::Image::scale(const std::string &path, const cds::ECoverSizes::Enum &type, const std::string &key)
path temporary folder to put images to
image uri
Referenced by cds::mod::ModAlbums::import.