cds
typedef std::shared_ptr< Config > cds::config_ptr
configuration ptr
const bool cds::CDS_DEBUG
const std::string cds::LOGGER
const std::string cds::VERSION
const int cds::SLEEP
const std::string cds::EVENT_SCANNER
const std::string cds::EVENT_RESCAN
const std::string cds::EVENT_START
const std::string cds::EVENT_END
const char* cds::PARAM_TMP_DIRECTORY
const char* cds::PARAM_TMDB_KEY
const char* cds::PARAM_AMAZON_KEY
const char* cds::PARAM_AMAZON_ACCESS_KEY
const char* cds::PARAM_REDIS
const char* cds::PARAM_REDIS_PORT
const char* cds::PARAM_LISTEN_ADDRESS
const char* cds::PARAM_HTTP_PORT
const char* cds::PARAM_DIRECTORY
static std::vector< std::string > cds::trash_words({"flac","24bit","720p","1080p","amzn","webrip","dd5.1","x264","mkv","hdtv","web-dl","h264","bdrip","dts","bluray","-hdc","mp4","-2hd","-rarbg","[rarbg]","-fgt","-japhson","-fgt","-ntb","-moritz","-avs","-dumbension","-it00nz","-cravers","-rovers","-sparks","[96-24]","audio fidelity","180g lp","24-96"})
static std::vector< std::string > cds::skip_words({"the ","der ","die ","das "})
static std::array< std::string, 3 > cds::album_cover_names({{"cover","front","folder"}})
static std::array< std::string, 6 > cds::metadata_relations({{"allmusic","IMDb","official homepage","image","wikipedia","discogs"}})
std::string cds::remove_skip_list(const std::vector< std::string > &words, const std::string &s)
std::string cds::clean_string(const std::string &s)
std::string cds::path(const std::string &filename)
std::string cds::filename(const std::string &filename, bool extension=true)
std::string cds::remove_extension(const std::string &file)
std::string cds::clean_isbn(std::string isbn)
std::string cds::clean_track_number(const std::string &track)
rapidxml_ns::xml_node* cds::element(rapidxml_ns::xml_document<> *doc, T *parent, const std::string &name, const std::string &value)
void cds::attr(rapidxml_ns::xml_document<> *doc, T *parent, const std::string &name, const std::string &value)
std::string cds::_get_ip()
DOC_INTERNAL std::vector< std::error_code > cds::validate(std::shared_ptr< Config > config)
config configuration to validate
References make_error_code.
Referenced by make_error_code.
std::string cds::json(std::shared_ptr< Config > config)
config configuration to output
Referenced by make_error_code.
std::shared_ptr< Config > cds::json(const std::string &config)
config configuration string to parse
std::error_code cds::make_error_code(int error)
make cds config error code
References make_error_code, validate, json.
Referenced by validate, make_error_code.