data::NodeType
Enum
static std::string data::NodeType::str(const Enum type)
node type as string.
Referenced by cds::mod::ModAlbums::import, cds::Scanner::import_files, cds::Scanner::flush, cds::Server::files.
static Enum data::NodeType::parse(const std::string &type)
get type from string.
Referenced by cds::mod::ModAlbums::import, cds::Scanner::import_files, cds::Server::files.
static bool data::NodeType::valid(const std::string &type)
is the type string valid.