data
typedef std::shared_ptr< redox::Redox > data::redis_ptr
typedef std::map< std::string, std::string > data::node_t
typedef std::set< std::string > data::nodes_t
typedef std::function< void(const std::string&) > data::async_fn
typedef std::vector< std::string > data::command_t
static unsigned long data::time_millis()
current timestamp in millis.
Referenced by cds::mod::ModAlbums::import, cds::mod::ModImages::import, cds::Scanner::import_files, cds::Scanner::flush.
static std::string data::hash(const std::string &in)
in string to hash.
Referenced by cds::mod::ModAlbums::import, cds::Scanner::import_files.
static bool data::is_mod(const std::string &path)
check if path is a mod path
Referenced by cds::Scanner::import_files.
static std::string data::make_key(const std::string &prefix, const std::string &value, ARGS...args)
prefix the prefix of the string
Referenced by files, add_nodes, rem_nodes, incr_mime, cds::mod::ModAlbums::import, cds::Scanner::import_files, cds::Server::status, cds::Server::sort, cds::Server::keywords.
static std::string data::make_key_node(const std::string &key)
key node key.
Referenced by get, set, cds::mod::ModAlbums::import, cds::Scanner::import_files, cds::Server::node.
static std::string data::make_key_list(const std::string &key)
key node key.
Referenced by add_types, rem_types, add_nodes, rem_nodes, cds::mod::ModAlbums::import.
static std::string data::make_key_list(const NodeType::Enum &type)
type node type.
static redis_ptr data::make_connection(const std::string db, int port)
db database host
static std::string data::get(redis_ptr redis, const std::string &key, const std::string param)
redis the database pointer.
References make_key_node.
Referenced by cds::mod::ModImages::import, cds::Scanner::import_files, cds::Scanner::flush, cds::Server::path.
static void data::set(redis_ptr redis, const std::string &key, const std::string param, const std::string value)
redis the database pointer.
References make_key_node.
Referenced by cds::mod::ModAlbums::import.
static void data::save(redis_ptr redis, const std::string &key, const node_t &node)
redis pointer to redis database.
Referenced by cds::mod::ModAlbums::import, cds::mod::ModImages::import, cds::Scanner::import_files, cds::Scanner::flush.
static node_t data::node(redis_ptr redis, const std::string &key)
redis redis database pointer.
Referenced by cds::mod::ModAlbums::import, cds::mod::ModImages::import, cds::Server::nodes, cds::Server::files.
static void data::children(redis_ptr redis, const std::string &key, const int &index, const int &count, const std::string &sort, const std::string &order, const std::string &filter, async_fn fn)
redis redis database pointer.
Referenced by cds::mod::ModAlbums::import, cds::Scanner::import_files, cds::Scanner::flush, cds::Server::nodes, cds::Server::files.
static void data::files(redis_ptr redis, const std::string &key, const NodeType::Enum type, const int &index, const int &count, async_fn fn)
redis redis database pointer.
References make_key.
Referenced by cds::Server::files.
static int data::children_count(redis_ptr redis, const std::string &key)
get the node children count
Referenced by cds::Server::status, cds::Server::nodes.
static int data::files_count(redis_ptr redis, const std::string &key, const NodeType::Enum type)
get the node children count
Referenced by cds::Server::files.
static void data::add_tag(redis_ptr redis, const std::string &name, const std::string &keyword, const NodeType::Enum &type, const std::string &node, float score)
redis redis database pointer.
Referenced by cds::mod::ModAlbums::import, cds::mod::ModImages::import.
static void data::eval(redis_ptr redis, const std::string &script, int argc, ARGS...argv)
redis the database pointer.
Referenced by cds::Scanner::import_files, cds::Scanner::flush.
static void data::add_types(redis_ptr redis, const std::string &path, const std::string &key, const unsigned long &score)
add node to parents type list
References make_key_list.
Referenced by cds::mod::ModAlbums::import, cds::Scanner::import_files, cds::Scanner::flush.
static void data::rem_types(redis_ptr redis, const std::string &parent, const std::string &key)
remove node from parents type list
References make_key_list.
Referenced by cds::mod::ModAlbums::import, cds::Scanner::import_files.
static void data::add_nodes(redis_ptr redis, NodeType::Enum type, const std::string &key, unsigned long score)
add node to global nodes list
References make_key_list.
Referenced by cds::mod::ModAlbums::import, cds::mod::ModImages::import, cds::Scanner::import_files.
static void data::rem_nodes(redis_ptr redis, NodeType::Enum type, const std::string &key)
remove node from global nodes list
References make_key_list.
Referenced by cds::mod::ModAlbums::import, cds::Scanner::import_files.
static void data::add_nodes(redis_ptr redis, const std::string &parent, const NodeType::Enum type, const std::string &key, unsigned long score)
add node to global nodes list
References make_key.
static void data::rem_nodes(redis_ptr redis, const std::string &parent, const NodeType::Enum type, const std::string &key)
remove node from global nodes list
References make_key.
static void data::incr_mime(data::redis_ptr redis, const std::string &mime_type)
redis redis database pointer.
References make_key.
Referenced by cds::Scanner::import_files.
static std::string data::config(redis_ptr redis)
redis redox database.
Referenced by cds::Server::config.
static void data::config(redis_ptr redis, const std::string &json)
redis redox database. c the configuration as json string.
static bool data::config_exists(redis_ptr redis)
redis redox database pointer.
static void data::__iterate_key(std::string &key, const std::string &value)
static void data::__iterate_key(std::string &key, const std::string &value, ARGS...args)
static std::map< std::string, std::string > data::to_map(command_t in)
data::FRIEND_TEST(DatastoreTest, to_map)